version: "2"

run:
  timeout: 3m
  go: "1.25"
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - bodyclose
    - noctx

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
    errcheck:
      check-type-assertions: true
      check-blank: true

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - loadtest
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - org-api
    golines:
      max-len: 120
  exclusions:
    paths:
      - loadtest
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0